### ISSUE TITLE
error on v8 installation of account_prepayment

### ISSUE THREAD

**Issue by ygol** [Elico-Corp/odoo-8.0#127]
Trying to install account_prepayment on two different server, I get the error:

`
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 900, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 977, in convert_xml_import
    relaxng.assert_(doc)
  File "lxml.etree.pyx", line 3313, in lxml.etree._Validator.assert_ (src/lxml/lxml.etree.c:159862)
AssertionError: Did not expect element record there, line 4
`

**Comment by elicoidal** [comment]
@ygol thanks for reporting the issue.
We will have a look and come back to you ( @noahzaozao )

**Comment by jankowa** [comment]
same here.
odoo 8.0 (debian jessie dep nightly build)

before the python traceback in the odoo log appears:

```
2017-01-19 14:44:58,438 105 INFO datenkollektiv-001 openerp.modules.loading: loading account_prepayment/views/account_view.xml
2017-01-19 14:44:58,445 105 ERROR datenkollektiv-001 openerp.tools.convert: The XML file does not fit the required schema !
2017-01-19 14:44:58,446 105 ERROR datenkollektiv-001 openerp.tools.convert: /usr/lib/python2.7/dist-packages/openerp/addons/account_prepayment/views/account_view.xml:4:0:ERROR:RELAXNGV:RELAXNG_ERR_ELEMWRONG: Did not expect element record there
2017-01-19 14:44:58,447 105 ERROR datenkollektiv-001 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):


```

**Comment by elicoidal** [comment]
@noahzaozao up!

**Comment by sebytza05** [comment]
Hey, 
I have the same error at installation:
"AssertionError: Did not expect element record there, line 4"
Please help

**Comment by noahzaozao** [comment]
@ygol @elicoidal @seb-elico @sebytza05 @jankowa this issue has been fixed https://github.com/Elico-Corp/odoo-addons/pull/146
