### ISSUE TITLE
Run "Py3o Demo Report": BadZipfile: File is not a zip file

### ISSUE THREAD

**Issue by sagasm** [Elico-Corp/odoo-8.0#200]
Traceback (most recent call last):
  File "J:\odoo10-x64\myaddons\report_py3o\controllers\main.py", line 84, in report_download
    reportname, docids=docids, converter='py3o')
  File "J:\odoo10-x64\source\odoo\http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "J:\odoo10-x64\myaddons\report_py3o\controllers\main.py", line 52, in report_routes
    res, filetype = py3o_report.create_report(docids, data)
  File "J:\odoo10-x64\myaddons\report_py3o\models\py3o_report.py", line 363, in create_report
    model_instance, data, save_in_attachment))
  File "J:\odoo10-x64\myaddons\report_py3o\models\py3o_report.py", line 304, in _get_or_create_single_report
    model_instance, data, save_in_attachment)
  File "J:\odoo10-x64\myaddons\report_py3o\models\py3o_report.py", line 244, in _create_single_report
    template = Template(in_stream, out_stream, escape_false=True)
  File "J:\odoo10-x64\runtime\python\lib\site-packages\py3o\template\main.py", line 408, in __init__
    self.infile = zipfile.ZipFile(self.template, 'r')
  File "J:\odoo10-x64\runtime\python\lib\zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "J:\odoo10-x64\runtime\python\lib\zipfile.py", line 835, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file

**Comment by elicoidal** [comment]
@sagasm thanks for reporting. 

Unfortunately I am not sure that I have enough information to answer your question. Besides, it seems that this is related to report_py3o module which is not hosted in our repository but in https://github.com/OCA/reporting-engine.

Please do not hesitate to provide more information and reopen this issue or open an issue in the OCA repository.
